name: sreu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - numpy=1.18.4
  - scipy=1.4.1
  - astropy=4.0.1
  - sunpy=1.1.4
  - matplotlib=3.2.1
  - heliopy=0.11.1
  - plasmapy=0.3.1
  - jupyter
  - pandas
  - pytest
  - pytest-astropy
  - pip
  - pip:
    - mpmath
    - lmfit
    - astroquery
    - jplephem
